var = {'id': '3918788', 'name': 'Global group LTD ( Яндекс Такси Алматы)', 'url': 'https://api.hh.ru/employers/3918788',
       'alternate_url': 'https://hh.ru/employer/3918788',
       'logo_urls': {'original': 'https://hhcdn.ru/employer-logo-original/697585.png',
                     '240': 'https://hhcdn.ru/employer-logo/3231457.png',
                     '90': 'https://hhcdn.ru/employer-logo/3231456.png'},
       'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=3918788', 'open_vacancies': 0}

var3 = {'id': '88747107', 'premium': False, 'name': 'Диспетчер поддержки (чаты/звонки), удаленно', 'department': None,
       'has_test': False, 'response_letter_required': False,
       'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
       'salary': {'from': 30000, 'to': 44000, 'currency': 'RUR', 'gross': True},
       'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
       'published_at': '2023-10-27T12:33:49+0300', 'created_at': '2023-10-27T12:33:49+0300', 'archived': False,
       'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=88747107',
       'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/88747107?host=hh.ru',
       'alternate_url': 'https://hh.ru/vacancy/88747107', 'relations': [],
       'employer': {'id': '9498120', 'name': 'Яндекс Команда для бизнеса', 'url': 'https://api.hh.ru/employers/9498120',
                    'alternate_url': 'https://hh.ru/employer/9498120',
                    'logo_urls': {'original': 'https://hhcdn.ru/employer-logo-original/1121425.jpg',
                                  '90': 'https://hhcdn.ru/employer-logo/6106293.jpeg',
                                  '240': 'https://hhcdn.ru/employer-logo/6106294.jpeg'},
                    'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=9498120', 'accredited_it_employer': False,
                    'trusted': True}, 'snippet': {
        'requirement': 'Опыт работы не требуется. Обязательно наличие ПК или ноутбука. Будет плюсом опыт работы на вакансиях:',
        'responsibility': None}, 'contacts': None, 'schedule': {'id': 'remote', 'name': 'Удаленная работа'},
       'working_days': [], 'working_time_intervals': [],
       'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
       'accept_temporary': False, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
       'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
       'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False,
       'adv_context': None}